import maya.cmds as mc
import maya.mel as mel

skeletonDefinition = {
	"Hips": 1,
	"LeftUpLeg": 2,
	"LeftLeg": 3,
	"LeftFoot": 4,
	"RightUpLeg": 5,
	"RightLeg": 6,
	"RightFoot": 7,
	"Spine": 8,
	"LeftArm": 9,
	"LeftForeArm": 10,
	"LeftHand": 11,
	"RightArm": 12,
	"RightForeArm": 13,
	"RightHand": 14,
	"Head": 15,
	"LeftToeBase": 16,
	"RightToeBase": 17,
	"LeftShoulder": 18,
	"RightShoulder": 19,
	"Neck": 20,
	"Spine1": 23,
	"Spin2": 24,
	"Spine3": 25,
	"Neck1": 32,
	"LeftHandThumb1": 50,
	"LeftHandThumb2": 51,
	"LeftHandThumb3": 52,
	"LeftHandThumb4": 53,
	"LeftHandIndex1": 54,
	"LeftHandIndex2": 55,
	"LeftHandIndex3": 56,
	"LeftHandIndex4": 57,
	"LeftHandMiddle1": 58,
	"LeftHandMiddle2": 59,
	"LeftHandMiddle3": 60,
	"LeftHandMiddle4": 61,
	"LeftHandRing1": 62,
	"LeftHandRing2": 63,
	"LeftHandRing3": 64,
	"LeftHandRing4": 65,
	"LeftHandPinky1": 66,
	"LeftHandPinky2": 67,
	"LeftHandPinky3": 68,
	"LeftHandPinky4": 69,
	"RightHandThumb1": 74,
	"RightHandThumb2": 75,
	"RightHandThumb3": 76,
	"RightHandThumb4": 77,
	"RightHandIndex1": 78,
	"RightHandIndex2": 79,
	"RightHandIndex3": 80,
	"RightHandIndex4": 81,
	"RightHandMiddle1": 82,
	"RightHandMiddle2": 83,
	"RightHandMiddle3": 84,
	"RightHandMiddle4": 85,
	"RightHandRing1": 86,
	"RightHandRing2": 87,
	"RightHandRing3": 88,
	"RightHandRing4": 89,
	"RightHandPinky1": 90,
	"RightHandPinky2": 91,
	"RightHandPinky3": 92,
	"RightHandPinky4": 93
}

def setCharacterDefinition(characterJoint, hikCharacter, definitionId):
        mel.eval('setCharacterObject("{}", "{}", "{}", "{}")'.format(characterJoint, hikCharacter, definitionId, 0))
